version: '3.8'

services:
  java-application:
    image: event-application
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EventTicketManagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379


  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: EventTicketManagement
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root