server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/EventTicketManagement # have changed port from 5432 -> 5433. TODO: change back if you need
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop